[Notification service] BaseEvent 添加sender字段
alibaba/flink-ai-extended pull request #252
Opened 2021-05-11 09:08 UTC by wuchaochen

## What is the purpose of the change

Notification service BaseEvent 对象添加sender字段代表发送事件的标识。

## Brief change log

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests.

2021-05-11 09:14 UTC, SteNicholas requested changes

2021-05-11 09:14 UTC, SteNicholas commented on flink-ai-flow/lib/airflow/airflow/models/baseoperator.py
> +        :param from_task_id: which task send the event
The comment of `from_task_id` should be after the `event_namespace `.

2021-05-11 09:51 UTC, SteNicholas commented on flink-ai-flow/lib/airflow/airflow/models/baseoperator.py
>          :rtype: Set[str, str, str]
The comment of the return type should update to `Set[str, str, str, str]`.

2021-05-11 09:54 UTC, SteNicholas commented
@wuchaochen , notification service has already updated, therefore the Java client of notification service should sync the change of service.

2021-05-17 14:37 UTC, jiangxin369 commented on flink-ai-flow/lib/notification_service/notification_service/client.py
> +                namespace=self._default_namespace,
这里写死_default_namespace意思是client只能发自己namespace的event了吗？如果是的话_default_namespace在构造函数里默认值为None有点不合理，用default或者unassigned之类的是不是好一点，不然保存到数据库里之后会有歧义

2021-05-18 01:59 UTC, SteNicholas commented on flink-ai-flow/lib/notification_service/notification_service/client.py
> +                namespace=self._default_namespace,
Notification client only send the events of the namespace from the constructor. And notification client could listen events from different namespaces.

2021-05-18 02:44 UTC, jiangxin369 approved these changes

2021-05-18 02:45 UTC, SteNicholas approved these changes

2021-05-18 02:56 UTC, merged