[Flink AI Flow] Refractor scheduler service
alibaba/flink-ai-extended pull request #472
Opened 2021-08-11 09:30 UTC by bgeng777

## What is the purpose of the change
#436 

## Brief change log

1. Add SchedulerConfig in scheduler_interface.py and move SchedulerFactory to this file as well.
2. Add validation check in SchedulerConfig and SchedulerServiceConfig constructors.
3. Adjust package organization of scheduler_service
4. Scheduler config in yaml changed as follows:
Old:
```yaml
scheduler:
  repository: /tmp
  scheduler_class: ai_flow_plugins.scheduler_plugins.airflow.airflow_scheduler.AirFlowScheduler
  scheduler_config:
    airflow_deploy_path: /tmp/airflow
    notification_service_uri: localhost:50051
```

New:
```yaml
scheduler_service:
  repository: /tmp
  scheduler:
    scheduler_class: ai_flow_plugins.scheduler_plugins.airflow.airflow_scheduler.AirFlowScheduler
    scheduler_config:
      airflow_deploy_path: /tmp/airflow
      notification_service_uri: localhost:50051
```

## Verifying this change

This change is already covered by existing tests, such as *(please describe tests)*.

2021-08-11 13:00 UTC, SteNicholas requested changes

2021-08-11 16:19 UTC, bgeng777 commented
During the refractor, I find a bug of current implementation of remote submission: 
In implementations of blob managers, there is a judge:
```python
        if local_path is not None:
            repo_path = Path(local_path)
        elif self._local_repo is not None:
            repo_path = Path(self._local_repo)
```
`local_path` is from scheduler while `_local_repo` is from the config in blob manager.


Then in `SchedulerServiceConfig`, there is a method:
```python
    def repository(self):
        if 'repository' not in self:
            return '/tmp'
        else:
            return self['repository']
```

but  'repository'  will always be in `self`. Because, in `_add_scheduler_service` method of `server.py`, we currently try to init like this:
```python
real_config.set_repository(scheduler_service_config.get('repository'))
```
In this way, if we do not declare 'repository' in `scheduler` config in `aiflow_server.yaml`,  `scheduler_service_config.get('repository')` will return None, as a result, `set_repository` will make `real_config['repository'] = None`. Finally, `repository`  will always be in `self`.

2021-08-12 06:36 UTC, jiangxin369 approved these changes

2021-08-12 08:23 UTC, SteNicholas requested changes

2021-08-12 08:23 UTC, SteNicholas commented on flink-ai-flow/ai_flow/plugin_interface/scheduler_interface.py
> +                'The `{}` option is not configured. Please add the `{}` option!'.format('scheduler',
```suggestion
                'The `{}` option is not configured. Please add the `{}` option under the `scheduler_service` option!'.format('scheduler',
```

2021-08-12 08:23 UTC, SteNicholas commented on flink-ai-flow/ai_flow/plugin_interface/scheduler_interface.py
> +    SchedulerFactory creates scheduler() based on configuration information.
```suggestion
    SchedulerFactory creates scheduler based on configuration information.
```

2021-08-12 08:41 UTC, SteNicholas approved these changes

2021-08-12 08:42 UTC, merged