[WIP][AIFlow][Bugfix][issue:475] remove unnecessary sleep in run_tests.sh
alibaba/flink-ai-extended pull request #484
Opened 2021-08-19 08:54 UTC by lisy09

## What is the purpose of the change

To fix the bug related to run_tests.sh & grpc UNAVAILABLE mentioned in #480.

## Brief change log

- add wait_for_ready(timeout:float=5) -> bool in 
  - AIFlowerServer
  - AIFlowerServerRunner
  - AIFlowClient
  - SchedulerClient
- for test cases running AIFlowerServer.start() / AIFlowerServerRunner.start(), call wait_for_ready() before first client call (including init_aiflow_context())
   - Use client's   call wait_for_ready() as much as possible
   - If it is difficult to add client's wait_for_ready(), use server's wait_for_ready

## Verifying this change 

This change is already covered by existing tests, such as *(please describe tests)*.

2021-08-19 12:08 UTC, lisy09 commented
As discussed with @SteNicholas, will move grpc.channel_ready_future logic to AIFlowClient.__init__(), and remove all modification to server side and test case.
Though it will brings behaviour change and impack quite large scale, it can benifit more as it fails faster in the client side when server not ready.

2021-08-20 03:41 UTC, lisy09 commented
@SteNicholas This pr is ready. Please help to check.

2021-08-20 03:51 UTC, SteNicholas requested changes

2021-08-20 03:51 UTC, SteNicholas commented on flink-ai-flow/ai_flow/client/ai_flow_client.py
> +            raise Exception(f"Server {self.server_uri} not ready!")
```suggestion
            raise Exception(f"Client connection to server({self.server_uri}) is not ready. Please confirm the status of the process for `AIFlowServer`.")
```

2021-08-20 03:54 UTC, lisy09 commented on flink-ai-flow/ai_flow/client/ai_flow_client.py
> +            raise Exception(f"Server {self.server_uri} not ready!")
fixed with https://github.com/alibaba/flink-ai-extended/pull/484/commits/bd81f30ef6402bcd9e940ae0e63177d343de0224

2021-08-20 05:37 UTC, SteNicholas approved these changes

2021-08-20 05:44 UTC, merged