feature(client&service):
alibaba/flink-ai-extended pull request #89
Opened 2020-12-18 11:55 UTC by MarvinMiao

1. support mongodb
2. add getLatestVersionByKey api in service

2020-12-18 11:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/flink-ai-extended?pullRequest=89) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/flink-ai-extended?pullRequest=89) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/flink-ai-extended?pullRequest=89) it.</sub>

2020-12-19 06:54 UTC, SteNicholas requested changes

2020-12-19 06:54 UTC, SteNicholas commented on flink-ai-flow/lib/notification_service/java/src/test/java/com/aiflow/notification/client/NotificationClientTest.java
> +		for(int i = 0; i <3; i++) {
This should add space to follow the code style.

2020-12-19 06:54 UTC, SteNicholas commented on flink-ai-flow/lib/notification_service/notification_service/base_notification.py
> +        :param key: event's key
The description of parameter `key` could be `Key of notification for listening.`.

2020-12-19 06:54 UTC, SteNicholas commented on flink-ai-flow/lib/notification_service/notification_service/base_notification.py
> +        get latest event's version by key
Add `.` at the end of this comment.

2020-12-19 06:54 UTC, SteNicholas commented on flink-ai-flow/lib/notification_service/notification_service/client.py
> +        get latest event's version by key
The same to above.

2020-12-19 06:54 UTC, SteNicholas commented on flink-ai-flow/lib/notification_service/notification_service/client.py
> +        :param key: event's key
The same to above.

2020-12-19 06:54 UTC, SteNicholas commented on flink-ai-flow/lib/notification_service/notification_service/event_storage.py
> +        print("#####mongo db conf: {}".format(str(db_conf)))
This print could be removed or recommend to use logging to log the MongoDB configuration.

2020-12-22 08:53 UTC, wuchaochen commented on flink-ai-flow/lib/notification_service/notification_service/event_storage.py
> +
add a new python file

2021-01-07 07:49 UTC, wuchaochen approved these changes

2021-01-07 07:49 UTC, merged